### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by Andduril** [FitnessForge/api#5]
## Description

This should be working buddy - The way she goes

## Tasks

- [ ]  Create the controller
- [ ] Create the service
- [ ] Add middleware to protect routes

## Links

links to docs
